### ISSUE TITLE
Bower.json - main options incorrect

### ISSUE THREAD

**Issue by leandrogf** [TheSharpieOne/angular-validation-match#25]
Please, modify bower.json, in the option "main" the value from "dist/angular-input-match.min.js" to "angular-validation-match.min.js".

**Comment by TheSharpieOne** [comment]
Does bower assume the files will be in a folder called "dist"?  Because that is the only place a file named "angular-validation-match.min.js" exists.  Looking at [bower docs for main](http://bower.io/docs/creating-packages/#main), I am not seeing how it would know.

**Comment by leandrogf** [comment]
I made a verification in the files and realized that wiredep not replace the value according to your modification. The bower.json is correct!!! Sorry my rush in the diagnostic!!
