### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by zzzaaa** [TheSharpieOne/angular-validation-match#26]
404 https://rawgit.com/TheSharpieOne/angular-input-match/master/dist/angular-input-match.min.js

**Comment by delasky** [comment]
the url should be https://rawgit.com/TheSharpieOne/angular-input-match/master/dist/angular-validation-match.min.js

here is a working version http://jsfiddle.net/q300sku2/45/

**Comment by TheSharpieOne** [comment]
Sorry about that, one of the side effects for changing the repo name.  I'll update the link in the README
