### ISSUE TITLE
combine with other validators

### ISSUE THREAD

**Issue by zzzaaa** [TheSharpieOne/angular-validation-match#27]
I tried to combine validation-match with other default validators. (minlegth)
For example: password should be longer then 8 chars. 
If you try to fill "123"  into password and confirm password input, you'll see "Passwords do not match!", but it equal.
Sample http://jsfiddle.net/5oy3mj1q/1/

**Comment by TheSharpieOne** [comment]
See the last section of the read me about matching the view value. 
http://jsfiddle.net/5oy3mj1q/2/

**Comment by zzzaaa** [comment]
For history: replace match="user.password" to match="form.password"

Thanks. Its work.
