### ISSUE TITLE
Angular <1.2 Dependency Version

### ISSUE THREAD

**Issue by eddie** [TheSharpieOne/angular-validation-match#31]
From the bower.json file

```
"dependencies": {
        "angular": ">=1.2.0 <2.0.0"
    },
```
https://github.com/TheSharpieOne/angular-validation-match/blob/master/bower.json#L36

From my understanding, this will cause issues with bower if you're using a version of angular > 1.2 - I'm not aware of any compatibility issues with 1.3, is there any reason for this?

Cheers!

**Comment by TheSharpieOne** [comment]
It's supposed to be greater than or equal to angular 1.2.0 and less than angular 2.0.0 which includes 1.2.x, 1.3.x, and 1.4.x
The issue you are probably having deals with version resolution in bower. If multiple packages want the same package at different versions (or even the same version with a range) bower will ask you which version of that package you want. You can persist your selection to not be prompted.

**Comment by eddie** [comment]
Err- I'm feeling pretty silly right now, I jumped the gun with this before my brain had started working for the day..

1.2 !== 2.0  Mistook v2 for v1.2, sorry for waiting your time @TheSharpieOne
