### ISSUE TITLE
Buggy behaviour when match="" (empty value)

### ISSUE THREAD

**Issue by leibrug** [TheSharpieOne/angular-validation-match#39]
When I put no value into `match` attribute, I'm getting validation error when filling my `<input>`.

I would expect no validation in case `match=""`.

Demo: http://jsfiddle.net/nr8cLwyp/2/
(Enter anything into _confirm_ field: no matter what _password_ value is, you get validation error and it won't disappear.)

I'm going to make pull request with fix.

**Comment by TheSharpieOne** [comment]
fixed in 22c809d
