### ISSUE TITLE
using not-match = true

### ISSUE THREAD

**Issue by JasemQabazard** [TheSharpieOne/angular-validation-match#41]
```
            <div class="form-group has-feedback" ng-class="{'has-error': enterRecitalForm.recitalCode.$error.required && !enterRecitalForm.recitalCode.$pristine}">
                <div class="col-xs-12 col-sm-offset-1 col-sm-10">
                    <i class="glyphicon glyphicon-pencil form-control-feedback"></i>
                    <input type="text" class="form-control" id="recitalCode" name="recitalCode" 
                           placeholder="Enter Recital Code*" match ="crc" not-match="true" ng-model="recitalCode" required>
                    <span ng-show="enterRecitalForm.recitalCode.$error.required && !enterRecitalForm.recitalCode.$pristine" class="help=block error">Enter Recital Code</span>
                </div>
            </div>
```

It works at form level the form becomes invald
except 
could not figure out how to display a customer span error I tried 
<span ng-show="enterRecitalForm.enterRecitalForm.$error.match && !enterRecitalForm.enterRecitalForm.$pristine" class="help=block error">Recital code must not match existing Code!</span>
but did not work 
is there a solution 
Regards

**Comment by JasemQabazard** [comment]
<span ng-show="enterRecitalForm.enterRecitalForm.$error.match && !enterRecitalForm.enterRecitalForm.$pristine" class="help=block error">Recital code must not match existing Code!</span>
This is what I tried

**Comment by JasemQabazard** [comment]
ng-show="enterRecitalForm.enterRecitalForm.$error.match && !enterRecitalForm.enterRecitalForm.$pristine" class="help=block error">Recital code must not match existing Code!

**Comment by TheSharpieOne** [comment]
Angular's validation pipelines add the error to `form.field.$error`. The key for this validation is `match` so it becomes `form.field.$error.match`
Using your form name and field name, it would be:

```
<span ng-show="enterRecitalForm.recitalCode.$error.match">Recital code must not match existing Code!</span>
```

Adding the `&& !enterRecitalForm.enterRecitalForm.$pristine` or `&& !enterRecitalForm.enterRecitalForm.$touched` will ensure it only shows when the field has changed or been blurred.

This is already somewhat documented in the readme.

If this not working for you, reopen the issue with more details and a fiddle or plunkr or something like that.
