### ISSUE TITLE
Match fields display as invalid when matches are chained

### ISSUE THREAD

**Issue by simondrabble** [TheSharpieOne/angular-validation-match#42]
I have the following situation (described at https://plnkr.co/edit/Pbo6muD9ga60duJr9g1a?p=preview)

A current password field.
A new password field, with match on the current field and not-match = true (so a user can't re-use their existing password).
A confirm password field, matching on the new field.

I'm using $viewValues to match against.

Steps:

1. enter a value in the new field
2. enter the same value in the confirm field.
3. enter the same value in the current field.

Observed:

The confirm field's $error.match is set to true

Expected:

The confirm field's $error.match is false, since it does in fact match the new field.

Tested on angular 1.5.8, AVM 1.9.0

Edit: fixed plunker link

**Comment by TheSharpieOne** [comment]
I think you might have forgot to save that plnkr.

I put this together and cannot reproduce: http://jsfiddle.net/TheSharpieOne/n6s1oywf/

**Comment by simondrabble** [comment]
I updated the link. Try this: https://plnkr.co/edit/Pbo6muD9ga60duJr9g1a?p=preview

**Comment by simondrabble** [comment]
The only difference I see between yours and mine is you seem to be using the $viewValue to match against, where I'm using the $modelValue (I thought I was using the $viewValue). I tried using the $viewValue and I get the expected behaviour.

**Comment by TheSharpieOne** [comment]
The reason `$modelValue` cannot be used is because when the field is _invalid_ the `$modelValue` is `undefined`
